myStr = "hell World"
print(dir(myStr))
print(myStr.upper())
print(myStr.lower())
print(myStr.swapcase())
print(myStr.replace('hell', 'heaven').upper())
print(myStr.count('h'))
print(myStr.startswith('h'))
print(myStr.endswith('World'))
print(myStr.find('noesta'))
print(myStr.index('e'))
print(myStr[-3])
print(f"my str is {myStr}")
print(f"my str is {myStr}")